### ISSUE TITLE
Scroll to bottom bug in todo-list

### ISSUE THREAD

**Issue by kartikayasija** [DevilsAutumn/Opensource-init#65]
**Title**
Scroll to bottom bug in todo-list

**Project link**
[Click here](https://github.com/kartikayasija/Opensource-init/tree/main/Web/Html%2CCSS%2CJavascript/todo-list)

**Domain**
Add 'x' inside [ ] to cross check box.

- [ ] App with Flutter
- [ ] App with Java
- [ ] App with Kotlin
- [x] Web with Html,css javascript
- [ ] Web with React

**Describe the bug**
- When a new item is added to the list, it doesn't scroll to bottom.
- Alert comes when we refresh or start the project.

**Expected behavior**
- When a new item is added, it should automatically scroll to bottom.
- Alert should only come when we try to add a blank item in the list.

**Screenshots**

<img width="949" alt="image" src="https://github.com/DevilsAutumn/Opensource-init/assets/115306535/a06c6b58-fa74-486b-a240-f0788c08930d">
<img width="959" alt="image" src="https://github.com/DevilsAutumn/Opensource-init/assets/115306535/9753c3f0-500c-4403-ae86-aeb56de8514d">

**Additional context**
Add any other context about the problem here else write NA.
